"""MITRE ATT&CK coverage report for the detection and hunting library."""

from __future__ import annotations

import re
from collections import defaultdict
from pathlib import Path

from .rules import load_rules

TACTIC_ORDER = [
    "Reconnaissance",
    "ResourceDevelopment",
    "InitialAccess",
    "Execution",
    "Persistence",
    "PrivilegeEscalation",
    "DefenseEvasion",
    "CredentialAccess",
    "Discovery",
    "LateralMovement",
    "Collection",
    "CommandAndControl",
    "Exfiltration",
    "Impact",
]
HUNT_HEADER = re.compile(r"^//\s*Tactic:\s*(?P<tactics>[^|]+)\|\s*Technique:\s*(?P<tech>.+)$", re.MULTILINE)


def _split_tactics(text: str) -> list[str]:
    return [t.strip().replace(" ", "") for t in text.split(",") if t.strip()]


def coverage(detections_dir: str | Path, hunting_dir: str | Path | None = None) -> dict[str, dict[str, set[str]]]:
    """Return {technique: {"tactics": {...}, "sources": {...}}}."""
    table: dict[str, dict[str, set[str]]] = defaultdict(lambda: {"tactics": set(), "sources": set()})
    for rule in load_rules(detections_dir):
        for tech in rule.data.get("relevantTechniques", []):
            table[tech]["tactics"].update(rule.data.get("tactics", []))
            table[tech]["sources"].add(f"rule: {rule.name}")
    if hunting_dir:
        for path in sorted(Path(hunting_dir).glob("*.kql")):
            m = HUNT_HEADER.search(path.read_text(encoding="utf-8"))
            if not m:
                continue
            for tech in re.findall(r"T\d{4}(?:\.\d{3})?", m.group("tech")):
                table[tech]["tactics"].update(_split_tactics(m.group("tactics")))
                table[tech]["sources"].add(f"hunt: {path.stem}")
    return table


def markdown(table: dict[str, dict[str, set[str]]]) -> str:
    lines = [
        "# MITRE ATT&CK coverage",
        "",
        "Generated by `secops coverage`. Do not edit by hand.",
        "",
        "| Technique | Tactics | Covered by |",
        "|---|---|---|",
    ]
    for tech in sorted(table):
        tactics = sorted(table[tech]["tactics"], key=lambda t: TACTIC_ORDER.index(t) if t in TACTIC_ORDER else 99)
        link = f"[{tech}](https://attack.mitre.org/techniques/{tech.replace('.', '/')}/)"
        lines.append(f"| {link} | {', '.join(tactics)} | {'<br>'.join(sorted(table[tech]['sources']))} |")
    covered = {t for v in table.values() for t in v["tactics"]}
    missing = [t for t in TACTIC_ORDER if t not in covered]
    lines += [
        "",
        f"**{len(table)} techniques across {len(covered & set(TACTIC_ORDER))} of {len(TACTIC_ORDER)} tactics.**",
    ]
    if missing:
        lines += ["", "Tactics with no coverage yet: " + ", ".join(missing) + "."]
    lines.append("")
    return "\n".join(lines)
